function G(a,c,e){function k(){0!=I&&(K=(new Date).getTime()-I)}function n(f){F=F|f;B.narme=F}function l(f){p.a("l2("+f+")");E=E|f;T()?(k(),I=0):0==I&&(I=(new Date).getTime());B.narm=E;p.a("l2e")}function r(f){L=L|f;B.naral=L}var p=new P,d=e&&e.dvObj||window.$dv,h=e&&e.impressionId||window.$uid,u=window.Pf||c,q=Array(u.hb),g=u.Wa/u.Wb+1,b=null,v="",x={},f=0,t=Array(u.hb),m={ea:{I:null,J:null,D:null,C:null,Oe:!1},g:{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,Oe:!1},va:{zb:null,yb:null},
Fb:0},w={},C={},A,y,z={},N={},J=null,Q=!1;this.Cb=function(f){if(null==J||1==J||8==J)J=f};for(c=0;c<u.hb;c++)t[c]="b"+c;var D={};e&&d&&d.CommonData&&(D.ctx=e.jb,D.cmp=e.ib,D.btreg=e.btreg,D.btadsrv=e.Qa,D.uid=e.ob,D.brid=d.CommonData.BrowserId,D.brver=d.CommonData.BrowserVersion,D.tstype=d.CommonData.Scenario);D.jsver=a?a:null;var B={},H={},I=0,K="",M="",L=0,E=0,F=0,O=0;this.Oc=function(){return I};this.rd=function(f){O=O|f;B.vct=O};this.qd=function(f){b=f;H.strp=b;this.qd=function(){}};this.$b=function(){return(new Date).getTime()};
var U=this.$b();this.Ee=function(){return U};this.qf=function(){E=E&-3;F=F&-2;F&=-3};this.Bb=function(){l(2)};this.Bf=function(){n(8);this.pc()};this.pc=function(){l(4)};this.md=function(){r(8);this.Bb()};this.xd=function(f){r(16);B.dbg9=f};this.yd=function(){r(1)};this.zf=function(){this.Bb();n(1)};this.yf=function(){this.Bb();n(2)};this.Za=function(f,b){l(8);M=p.xe(f,b)};this.vf=function(){p.a("l1");E=E&-3;l(1);p.a("l1e")};this.pd=function(){l(16)};this.re=function(){return q};this.nd=function(b,
a){h=h||e&&e.impressionId||window.$uid;p.a("ie15");if(0<=b.j){var m=Math.floor(b.j/u.Wb);0<b.j%u.Wb?m++:0<b.j&&m++;isNaN(q[m])&&(q[m]=0);q[m]+=a;b.P&&m>=g||0==b.P&&6<=m?f+=a:(timeStampTotalBuckets=f=0,this.Cb(7))}p.a("ie15e")};this.xf=function(f){var b=f.Vc;null!=f.Vc&&(w.advisonl=b);null!=f.Uc&&(w.adabvvponl=f.Uc);B.dbg8="CSS1Compat"===document.compatMode?1:0;p.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(B.dbg10=document.documentMode);p.a("ff52e")};this.Ya=function(f){p.a("ie14");
null!=f&&(N.adbtftopg=f)};this.wf=function(f){null!=f&&(m=f)};this.od=function(f){p.a("ie19");this.wf(f.s);this.Df();p.a("ie19e")};this.Bd=function(){null!=m.ea.I&&(z.vptoscrx=Math.round(m.ea.I));null!=m.ea.J&&(z.vptoscry=Math.round(m.ea.J));null!=m.ea.D&&(z.vpwdth=Math.round(m.ea.D));null!=m.ea.C&&(z.vphgt=Math.round(m.ea.C));null!=m.g.v&&(z.adtovpx=Math.round(m.g.v));null!=m.g.u&&(z.adtovpy=Math.round(m.g.u));null!=m.g.K&&(z.adtopgx=Math.round(m.g.K));null!=m.g.L&&(z.adtopgy=Math.round(m.g.L));
null!=m.g.G&&(z.adtoscrx=Math.round(m.g.G));null!=m.g.H&&(z.adtoscry=Math.round(m.g.H));null!=m.va.zb&&(z.scrwdth=Math.round(m.va.zb));null!=m.va.yb&&(z.scrhgt=Math.round(m.va.yb));z.almesind=m.Fb};this.Cd=function(){if(A&&y){var f=m.g.o,b=m.g.m;A*y<f*b&&(C.dvp_adwdth=Math.round(A),C.dvp_adhgt=Math.round(y),!Q&&(1>=A||1>=y)&&1<f&&1<b&&($dv.registerEventCall(h,{adwdth:Math.round(f),adhgt:Math.round(b)}),Q=!0),A=f,y=b)}else A=null!=m.g.o?m.g.o:null,y=null!=m.g.m?m.g.m:null;null!=A&&(C.adwdth=Math.round(A));
null!=y&&(C.adhgt=Math.round(y))};this.Df=function(){k();for(var f=0;f<q.length;f++)q[f]&&(x[t[f]]=q[f]);this.Bd();this.Cd();p.F(z,w);p.F(z,C);p.F(z,N)};this.Mc=function(){if(1E3<=f)return!0;this.Cb(8);return!1};this.Be=function(f){var b={};h=h||e&&e.impressionId||window.$uid;var g=-1,a=p.ye();try{d&&d.tags[h]&&d.tags[h].getTimeDiff&&(g=d.tags[h].getTimeDiff())}catch(m){}var q=[];p.F(b,D);switch(f){case 1:v=g;p.F(b,H);p.F(b,B);b.napt=K;p.F(b,z);b.dvp_log=a;b.napr=M;b.ismms=v;b.isumms=g;break;case 2:p.F(b,
H);p.F(b,B);b.napt=K;p.F(b,z);b.dvp_log=a;b.napr=M;b.isnmms=g;break;case 3:b.istoms=g,b.nvr=J;case 4:case 8:p.F(b,H);p.F(b,N);p.F(b,C);b.isbxdms=g;p.F(b,x);b.nvr=J;break;case 5:p.F(b,H);p.F(b,N);p.F(b,C);p.F(b,w);b.ismms=v||g;b.isiabvms=g;b.isuiabvms=g;break;case 16:p.F(b,H);p.F(b,B);b.napt=K;b.dvp_log=a;b.napr=M;b.ishems=g;break;case 7:return q.join("");default:p.F(b,H),p.F(b,x),p.F(b,B),p.F(b,w),b.napt=K,b.dvp_log=a,b.napr=M}b.evid=f;b.ctime=this.$b();return b};this.qe=function(){p.a("ie17");for(var f=
[],b=0;b<u.hb;b++)f[b]=q[b]?q[b]:0;return f};var T=this.Gc=function(){return 2==(E&2)&&8!=(L&8)||4==(E&4)||8==(F&8)&&8==(L&8)?!1:!0};this.hf=function(f){p.a("l3");f=p.ca(f);p.a("cm3e");f&&(B.dbg5=f.w,B.dbg6=f.h);p.a("l3e")};return this}function R(a,c){var e=new P,k=a&&a.impressionId||window.$uid;this.da=function(a,l){if(c){var r=c.Be(a);l&&e.F(r,l);var p=!1;if(4==a||8==a)p=!0;this.ld(k,r,p)}};this.ld=function(a,c,e){$dv&&$dv.registerEventCall&&a&&$dv.registerEventCall(a,c,null,null,e)}}
function S(){this.da=function(){};this.ld=function(){}}
function V(a,c,e,k){function n(){if(1==m){try{for(var b in f)t.removeChild(f[b]);v.document.body.removeChild(t)}catch(g){}m=!1}}function l(f){f=f||0;var b=d(0);b.Yc()?7<b.nb()?(n(),C=w=m=!1):(m=!0,w=!1):20>f?(f++,setTimeout(l,50,f)):(m=w=C=!1,n())}function r(f){$dv&&$dv.tags&&$dv.tags[k]&&$dv.tags[k].getTimeDiff&&$dv.tags[k].getTimeDiff();if(null!==f.eb)for(var b=0;b<f.eb.length;b++){var g=d(b).nb();0==b?g>A&&(A=g):g>y&&(y=g)}}function p(f){for(var b=!0,g=0;13>=g;g++)var h=d(g),b=b&(null!==h&&h.Yc());
if(!b)return null;f.Dc=0;f.nc=0;f.mc=0;f.gc=0;f.Ca=0;f.eb=Array(13);b=d(0).nb();for(g=1;13>=g;g++)if(h=5<Math.abs(d(g).nb()-b),f.eb[g]=h)switch(f.Dc++,g){case 2:case 3:case 4:case 5:f.nc++;break;case 6:case 7:case 8:case 9:f.mc++;break;case 10:case 11:case 12:case 13:f.gc++}if(13===f.Dc)return f.Ca=100,r(f),!0;b=f.eb;if(!1===b[1]){if(3<=f.gc||3<=f.mc||3<=f.nc)return r(f),null;f.Ca=0;r(f);return!1}if(!0===b[1]&&(!0===b[2]&&!0===b[3]||!0===b[2]&&!0===b[4]||!0===b[3]&&!0===b[5]||!0===b[4]&&!0===b[5])||
!0===b[1]&&4==f.mc||!0===b[1]&&4==f.gc&&1<=f.nc)return f.Ca=50,r(f),!0;if(b[2]&&b[5]&&!(b[6]&&b[10]&&b[1]&&b[13]&&b[9])||b[4]&&b[3]&&!(b[8]&&b[12]&&b[1]&&b[11]&&b[7]))return r(f),null;f.Ca=0;r(f);return!1}function d(b){b=f[b];var g=null;b&&(g=b.contentWindow);return g}function h(){for(var b=x.getBoundingClientRect(),h=b.width,a=b.height,m=h/(1+q),d=a/(1+q),t=h/q,u=a/q,v=0;13>=v;v++){var c=b.left,e=b.top;switch(v){case 0:e=c=-1E5;break;case 1:c+=(h-g)/2;e+=(a-g)/2;break;case 3:c+=h-g;break;case 4:e+=
a-g;break;case 5:c+=h-g;e+=a-g;break;case 6:c+=(h-t)/2;e+=(a-u)/2;break;case 7:c+=(h-t)/2+t;e+=(a-u)/2;break;case 8:c+=(h-t)/2;e+=(a-u)/2+u;break;case 9:c+=(h-t)/2+t;e+=(a-u)/2+u;break;case 10:c+=(h-m)/2;e+=(a-d)/2;break;case 11:c+=(h-m)/2+m;e+=(a-d)/2;break;case 12:c+=(h-m)/2;e+=(a-d)/2+d;break;case 13:c+=(h-m)/2+m,e+=(a-d)/2+d}6<=v&&(c-=g/2,e-=g/2);var w=f[v];w.style.left=c+"px";w.style.top=e+"px"}}function u(){if(null!=x&&null!=x.parentNode){w=!0;t=v.document.createElement("div");v.document.body.appendChild(t);
for(var b=0;13>=b;b++){var a=v.document.createElement("iframe");a.width=g;a.height=g;a.style.position="absolute";a.frameBorder="0";a.style.visibility="hidden";a.style.zIndex=-9999999;a.style.display="block";a.src="javascript:no=false;yes=true;("+function(){window.af={Zd:100};window.Kc=no;window.bb=0;window.Tc=0;window.ad=0;window.Sf=no;window.nb=function(){return window.ad};window.Yc=function(){return window.Kc};window.Ve=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Rb=function(){window.bb++;window.Ve(window.Rb,document)};window.Rb();setInterval(function(){10>window.bb&&window.Rb();window.ad=window.bb-window.Tc;window.Tc=window.bb},window.af.Zd);window.setTimeout(function(){window.Kc=yes},250)}.toString()+")();";t.appendChild(a);f.push(a)}h()}}var q=Math.sqrt(2),g=1,b=new P,v=null,x=null,f=[],t,m=!1,w=!1,C=b.ub(a,c,e);0==b.Ua()&&(g=8);var A=0,y=0;this.Ke=function(){0==w&&(0==(this.Va()&&(null!=x&&b.Xc(x,v)?!0:!1))?m=!1:(u(),
l()))};this.Va=function(){return C};this.Re=function(){return m};this.sd=function(f,b){v=f;x=b;this.Ke()};this.He=function(){if(0==m)return null;var f={};return null==p(f)?null:f.Ca}}
function W(a,c,e,k,n,l,r,p){this.b=new P;this.window=a;this.c=c;this.R=e;this.M=k;this.Z=r&&r.Enums.BrowserId||window.$dv.Enums.BrowserId;this.W=r&&r.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.N=n;this.ec=l;this.ga=null;this.Sc=this.window?this.b.vb(this.window.top):this.b.vb(window.top);this.Ne=this.R!=this.W.CrossDomain&&this.b.lb("ofs")&&this.Sc;this.ga=new V(this.R,this.M,r,p);null!=this.ga&&this.ga.Va()&&this.ga.sd(this.window,this.c);this.qb=this.wb=this.pa=null;this.rb=!1;
var d=0;this.ia={Nd:1,Od:2,Id:4,Kb:8,Hd:16,Lb:32,Md:64};this.oc=function(h,a,q,g){if(g&&g.insertBefore&&g.firstChild&&(h=this.window.document.createElement(h))){for(var b in a)h[b]=a[b];for(b in q)h.style[b]=q[b];g.insertBefore(h,g.firstChild);return h}return null};this.oe=function(h,a,q){var g=this.window.top,b=h.width,d=h.height;0>q.left?(b=h.width-Math.abs(q.left),0>a.Aa&&(b-=Math.abs(a.Aa))):0>a.Aa&&(b=h.width-Math.abs(a.Aa)+q.left,b=b>h.width?h.width:b);var c=h.width,f=Math.min(this.b.ya(g.window).clientWidth,
g.innerWidth),t=screen.availWidth-f-a.Aa,m=0;b<c?(c=b,m=f-b,0>a.Aa&&(m-=Math.abs(a.Aa))):m=f-c-q.left;0>m?(b=c-Math.abs(m),0>t&&(b-=Math.abs(t))):0>t&&(b=c-Math.abs(t)+m,b=b>c?c:b);a=screen.availHeight-a.rf-g.outerHeight;g=Math.min(this.b.ya(g.window).clientHeight,g.innerHeight)-h.height-q.top;0>g?(d=h.height-Math.abs(g),0>a&&(d-=Math.abs(a))):0>a&&(d=h.height-Math.abs(a)+g,d=d>h.height?h.height:d);0>q.top&&(d-=Math.abs(q.top));return{Gf:b,Hf:d}};this.Zb=function(a,d,q,g){var b=q.D,c=q.C,e=0;q=0;
var f={width:d.right-d.left,height:d.bottom-d.top};if(0>d.bottom||0>d.right||d.top>c||d.left>b||0>=f.width||0>=f.height)return 0;0>d.top?Math.abs(d.top)>=f.height?e=0:(e=f.height+d.top,e>c&&(e=c)):e=d.top+f.height>c?c-d.top:f.height;0>d.left?Math.abs(d.left)>=f.width?q=f.width:(q=f.width+d.left,q>b&&(q=b)):q=d.left+f.width>b?b-d.left:f.width;this.Ne&&(a=this.oe(f,a,d),q=a.Gf,e=a.Hf);return 0>=q||0>=e?0:Math.round(q*e/(f.width*f.height)*(g?f.width*f.height/((g.right-g.left)*(g.bottom-g.top)):1)*100)};
this.Yb=function(a,d){try{var q={x:a.offsetLeft,y:a.offsetTop},g;a.offsetParent?(g=this.Yb(a.offsetParent,d),q.x+=g.x,q.y+=g.y):d!=d.parent&&this.b.Mb(d,d.parent)&&(g=this.Yb(d.frameElement,d.parent),q.x+=g.x,q.y+=g.y);return q}catch(b){return{x:null,y:null}}};this.na=function(a){if(this.R==this.W.CrossDomain)if(this.b.ua(this.window)&&this.window.$sf.ext.geom)this.na=function(){var f=this.b.Ka(this.window),b=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-
parseInt(f.win.h):this.N.Explorer.X,g={D:null,C:null,I:null,J:null,i:!1};g.D=parseInt(f.win.w);g.C=parseInt(f.win.h);g.I=parseInt(f.win.l);g.J=parseInt(f.win.t)+b;g.i=!0;return g};else if(this.M.Y==this.Z.Firefox)this.na=function(){var f=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,b=f?0:this.window.screenX-screen.left,f=f?0:this.window.screenY-screen.top,g={D:null,C:null,I:null,J:null,i:!1};g.D=this.window.outerWidth;g.C=this.window.outerHeight-this.N.Firefox.X;g.I=b;g.J=
f+this.N.Firefox.X;g.i=!0;return g};else if(this.b.jc(this.window)){var d=this;this.window.context.observeIntersection(function(f){f.forEach(function(f){d.pa=f})});this.na=function(){var f={D:null,C:null,i:!1,I:null,J:null};null!=this.pa?(f.D=this.pa.rootBounds.width,f.C=this.pa.rootBounds.height):(f.D=0,f.C=0);f.i=!0;return f}}else if(this.M.Y==this.Z.IE&&/^[11|12]/.test(this.M.ta))this.na=function(){var f=-8==this.window.screenY&&-8==this.window.screenX,b=f?0:this.window.screenX,f=f?0:this.window.screenY,
g={D:null,C:null,I:null,J:null,i:!1};g.D=this.window.outerWidth;g.C=this.window.outerHeight-this.N.Explorer.X;g.I=b;g.J=f+this.N.Explorer.X;g.i=!0;return g};else if(this.M.Y==this.Z.IE&&/[6-9]|[10]/.test(this.M.ta)){var q=this.oc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,je:0,We:"0",Xe:"0"},{display:"inline",position:"absolute",top:0,left:0,Ff:"none",zIndex:0,border:0},this.window.document.body),g=this.oc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,je:0,We:"0",Xe:"0"},{display:"inline",
position:"absolute",top:0,left:0,Ff:"none",zIndex:0,border:0},this.window.document.body),b=g.contentWindow||g.window||g.contentDocument.window||g.contentWindow.window||this.window.Kf,c=q.contentDocument||q.contentWindow.document,q=g.contentDocument||g.contentWindow.document,e="<html><head><script >window.onload = "+function(f){f&&(window.event=f);isFinite(String(window.event.clientY))&&(parent.Ra={Pb:window.event.clientY,Ob:window.event.clientX,Ad:window.event.screenY-window.event.clientY-window.screenY})}.toString()+
"; \x3c/script></head><body></body></html>",g='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(f){f&&(window.event=f);isFinite(String(window.event.clientY))&&(parent.qa={Pb:window.event.clientY,Ob:window.event.clientX,Ga:window.event.screenY-window.event.y,Fa:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";q.open("text/html","replace");q.write(g);q.close();
c.open("text/html","replace");c.write(e);c.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.na=function(){b.runMoM();c.open("text/html","replace");c.write(e);c.close();var f=this.window.qa,g=this.window.Ra,a=screen.availWidth,d=screen.availHeight,g=g?g.Ad:this.N.Explorer.X;if(f){var h=f.Fa,q=f.Ga;f.Fa>=a&&(f.Fa-=a);f.Ga>=d&&(f.Ga-=d);var u={D:null,C:null,I:null,J:null,i:!1};u.D=this.window.outerWidth?this.window.outerWidth-
20:a-f.Fa-20;u.C=this.window.outerHeight?this.window.outerHeight-g-10:d-f.Ga-10;u.I=h;u.J=q;u.i=!0}else u={D:null,C:null,I:null,J:null,i:!1},u.D=this.window.outerWidth?this.window.outerWidth-20:a-20,u.C=this.window.outerHeight?this.window.outerHeight-g-10:d-10,u.I=null,u.J=null,u.i=!1;return u}}else this.b.tb()?(this.hd(),this.na=function(){this.rb||this.hd();var f={D:null,C:null,I:null,J:null,i:!1};f.D=this.window.outerWidth;f.C=this.window.outerHeight-this.N.Chrome.X;f.i=!1;return f}):this.na=this.M.Y==
this.Z.Chrome?function(){var f={D:null,C:null,I:null,J:null,i:!1},b=!1;try{f.D=this.window.frameElement.offsetParent.parentNode.clientWidth,f.C=this.window.frameElement.offsetParent.parentNode.clientHeight,b=!0}catch(g){}f.I=this.window.screenX;f.J=this.window.screenY;f.i=b;return f}:null!=this.ga&&this.ga.Va()?function(){var f={D:null,C:null,I:null,J:null,i:!1};f.D=this.window.outerWidth;f.C=this.window.outerHeight-this.N.Safari.X;f.i=!1;return f}:function(){return{D:null,C:null,I:null,J:null,i:!1}};
else this.na=function(){var f,b,g=this.window.top;void 0!=g.mozInnerScreenX&&null!=g.mozInnerScreenX?(f=g.mozInnerScreenX,b=g.mozInnerScreenY):void 0!=g.screenX&&null!=g.screenX?0!=g.screenLeft+8&&g.screenLeft+8!=screen.width||0!=g.screenTop+8&&g.screenTop+8!=screen.height?(f=g.screenLeft,b=g.screenTop+(g.outerHeight-g.innerHeight)):(f=g.screenLeft+8,b=g.screenTop+(g.outerHeight-g.innerHeight)+8):(f=g.screenLeft,b=g.screenTop);var a={D:null,C:null,I:null,J:null,i:!1},d=this.b.ya(g);a.D=g.innerWidth||
d.clientWidth;a.C=g.innerHeight||d.clientHeight;a.I=f;a.J=b;a.i=!0;return a};return this.na(a)};this.ma=function(a,c){d=1;this.R==this.W.CrossDomain?this.b.ua(this.window)&&this.window.$sf.ext.geom&&this.b.Ka(this.window).par?(d=8,this.ma=function(){var a=this.b.Ka(this.window),g=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(a.win.h):this.N.Explorer.X,b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};
b.v=parseInt(a.self.l)-parseInt(a.par.l);b.u=parseInt(a.self.t)-parseInt(a.par.t);b.K=parseInt(a.self.l);b.L=parseInt(a.self.t);b.G=parseInt(a.win.l)+b.v;b.H=parseInt(a.win.t)+b.u+g;b.o=parseInt(a.self.w);b.m=parseInt(a.self.h);b.i=!0;b.rect={top:b.u,bottom:b.u+b.m,left:b.v,right:b.v+b.o};return b}):this.M.Y==this.Z.Firefox?this.ma=function(){var a=1;window.devicePixelRatio&&(a=window.devicePixelRatio);var g=this.window.screenX,b=this.window.screenY,d=this.window.mozInnerScreenX/a-g,a=this.window.mozInnerScreenY/
a-b-this.N.Firefox.X,d={left:d,top:a,right:d+this.window.innerWidth,bottom:a+this.window.innerHeight},a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};a.v=d.left;a.u=d.top;a.K=null;a.L=null;a.G=g+d.left;a.H=b+d.top;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.i=!0;a.rect=d;this.b.Eb()&&(a=this.kb(a));return a}:this.b.jc(this.window)?(d=32,this.ma=function(){var a={v:null,u:null,o:null,m:null,i:!1,rect:null,O:null,oa:null,K:null,L:null,G:null,H:null};
null!=this.pa?(a.v=this.pa.boundingClientRect.left,a.u=this.pa.boundingClientRect.top,a.o=this.pa.boundingClientRect.width,a.m=this.pa.boundingClientRect.height):(a.v=0,a.u=0,a.o=0,a.m=0);a.i=!0;a.rect={top:a.u,bottom:a.u+a.m,left:a.v,right:a.v+a.o};return a}):this.M.Y==this.Z.IE&&/^[11|12]/.test(this.M.ta)?this.ma=function(a){var g=this.window.screenLeft-window.screenX,b=this.window.screenTop-window.screenY-this.N.Explorer.X,g={left:g,top:b,right:g+this.window.innerWidth,bottom:b+this.window.innerHeight},
b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};b.v=g.left;b.u=g.top;b.K=null;b.L=null;b.G=a.I+g.left;b.H=a.J+g.top;b.o=this.window.innerWidth;b.m=this.window.innerHeight;b.i=!0;b.rect=g;this.b.Eb()&&(b=this.kb(b));return b}:this.M.Y==this.Z.IE&&/[6-9]|[10]/.test(this.M.ta)?this.ma=function(){if(8==document.documentMode)return{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};var a=this.window.Ra&&this.window.qa?this.window.Ra.Pb-
this.window.qa.Pb:0,g=this.window.Ra&&this.window.qa?this.window.Ra.Ob-this.window.qa.Ob:0,b=this.b.ya(this.window),d={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};d.v=g;d.u=a;d.K=null;d.L=null;d.G=this.window.qa?g+this.window.qa.Fa:null;d.H=this.window.qa?a+this.window.qa.Ga:null;d.o=this.window.innerWidth||b.clientWidth;d.m=this.window.innerHeight||b.clientHeight;d.i=!0;d.rect={left:g,top:a,right:g+(this.window.innerWidth||b.clientWidth),bottom:a+(this.window.innerHeight||
b.clientHeight)};this.b.Eb()&&(d=this.kb(d));return d}:this.b.tb()?(d=512,this.ma=function(){var a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};null!=this.c&&(adData=this.b.mb(this.c),a.o=adData?adData.w:this.window.innerWidth,a.m=adData?adData.h:this.window.innerHeight);return a}):this.ma=this.M.Y==this.Z.Chrome?function(){var a=null,g=null,b=!1;try{var d=this.window.frameElement.offsetTop,a=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,
g=d-this.window.frameElement.offsetParent.scrollTop,b=!0}catch(h){}d={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null};d.v=a;d.u=g;d.K=null;d.L=null;d.G=null;d.H=null;d.o=this.window.innerWidth;d.m=this.window.innerHeight;d.i=b;d.rect=b?{left:a,top:g,right:a+this.window.innerWidth,bottom:g+this.window.innerHeight}:null;this.b.Eb()&&(d=this.kb(d));return d}:null!=this.ga&&this.ga.Va()?function(){var a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,
rect:null,O:null,oa:null};null!=this.c&&(adData=this.b.mb(this.c),a.o=adData?adData.w:this.window.innerWidth,a.m=adData?adData.h:this.window.innerHeight);return a}:function(){return{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null}}:this.ma=function(a){var g=this.Yb(this.c,this.window),b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,O:null,oa:null},d=this.b.ac(this.c,this.window),h=this.b.uc(this.c,this.window);b.v=h.left;b.u=h.top;b.K=
g.x;b.L=g.y;b.G=a.I+h.left;b.H=a.J+h.top;b.o=h.w;b.m=h.h;b.i=!0;b.rect=d;b.O=h;return b};return this.ma(a,c)};this.kb=function(a){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return a;var d=this.b.mb(this.c);if(d){var c=d.w,g=d.h,b=a.v,e=a.u,x=a.H,f=a.G;null!=a.v&&null!=a.u&&null!=a.m&&null!=a.o&&a.rect&&(0<d.t?(e=a.u+d.t,null!=a.H&&(x=a.H+d.t)):g+=d.t,0<d.l?(b+=d.l,null!=a.G&&(f=a.G+d.l)):c+=d.l,d.r>a.o&&(c-=d.r-a.o),d.Cc>a.m&&(g-=d.Cc-a.m),a.o=0<c?c:0,a.m=0<
g?g:0,a.v=b,a.u=e,a.H=x,a.G=f,a.rect.left=a.v,a.rect.top=a.u,a.rect.right=a.v+d.w,a.rect.bottom=a.u+d.h,a.O={w:c,h:g,left:b,right:b+c,top:e,bottom:e+g})}return a};this.De=function(){var a=screen.availWidth,d=screen.availHeight,c=screen.width,g=screen.height,b=0,e=0;this.Sc&&(e=this.window.top,b=e.screenX,e=e.screenY);return{i:this.N.Ua?!1:"undefined"!==typeof b,zb:a||c,yb:d||g,Qf:b,Rf:e,Aa:b-(c-a),rf:e-(g-d)}};this.me=function(){var a=this.De(),d=this.na(a),c=this.ma(d,a);return{ea:d,g:c,va:a,Fb:(null==
d.I||null==d.J?0:this.ia.Nd)|(null==d.D||null==d.C?0:this.ia.Od)|(null==c.v||null==c.u?0:this.ia.Id)|(null==c.K||null==c.L?0:this.ia.Kb)|(null==c.G||null==c.H?0:this.ia.Hd)|(null==c.m||null==c.o?0:this.ia.Lb)|(null==a.yb||null==a.zb?0:this.ia.Md),P:this.Hc(c.m,c.o)}};this.Hc=function(a,d){null==a&&(a=0);null==d&&(d=0);return 1!=this.N.Ua?242500<=a*d:!1};this.ue=function(){this.b.a("c10");if(null!=this.c)if(this.b.Xc(this.c,this.window))try{var a={timeStamp:new Date,j:-3,ja:-3,s:null,P:!1,fa:0};if(!this.ec())return a;
var c=this.me(),e;if(!c.g.i||!c.ea.i){if(this.b.ua(this.window)&&this.window.$sf.ext.inViewPercentage)return e=this.window.$sf.ext.inViewPercentage(),{timeStamp:new Date,j:e,ja:e,s:c,P:c.P,fa:16};if(this.b.tb()&&this.rb)return e=0,null!=this.qb&&(e=Math.round(100*this.qb.intersectionRatio)),{timeStamp:new Date,j:e,ja:e,s:c,P:this.Hc(c.g.m,c.g.o),fa:512};if(this.ga.Va()){var g={timeStamp:new Date,j:-3,ja:-3,s:null,P:!1,fa:2};if(0==this.ga.Re())g.j=-6,g.ja=-6,this.ga.sd(this.window,this.c);else{var b=
this.ga.He();null!=b&&(g.s=c,g.P=c.P,g.j=b,g.ja=b)}return g}a.s=c;d&&(a.fa=d);return a}if(c.g&&c.g.O&&(0===c.g.O.w||1===c.g.O.w||0===c.g.O.h||1===c.g.O.h))return{timeStamp:new Date,j:-5,ja:-5,s:c,fa:d};e=c.g.O?this.Zb(c.va,c.g.O,c.ea,c.g.rect):this.Zb(c.va,c.g.rect,c.ea);return{timeStamp:new Date,j:e,ja:e,s:c,P:c.P,fa:d}}catch(v){return{timeStamp:new Date,j:-4,ja:-4,s:null,P:!1,fa:d}}else return{timeStamp:new Date,j:-2,ja:-2,s:null,P:!1,fa:0};else return{timeStamp:new Date,j:-1,ja:-1,s:null,P:!1,
fa:0}};this.ne=function(a,d){this.b.a("c11");var c=null,g=null;if(null!=a.s){var b=a.s.g;d<=this.N.cf&&(c=0<=a.j||-5==a.j?a.P&&a.j>=this.N.Wa||0==a.P&&50<=a.j?!0:!1:null,g=a.P?this.N.Wa/100:.5,g=0==c?0>b.u+b.m*g?!0:!1:1==c?!1:null)}return{Uc:g,Vc:c}};this.sb=function(a){this.b.a("c12");var d=null;if(2!=a.fa&&512!=a.fa&&null!=a.s){var c=a.s.Fb,g=a.s.g;(c&this.ia.Kb)==this.ia.Kb&&(c&this.ia.Lb)==this.ia.Lb&&(d=this.Zb(a.s.va,{left:g.K,top:g.L,right:g.K+g.o,bottom:g.L+g.m},a.s.ea,g.rect),d=0<=a.j?a.P&&
d>=this.N.Wa||0==a.P&&50<=d?!1:!0:null)}this.b.a("c12e");return d};this.hd=function(){function a(d){d.forEach(function(a){c.qb=a})}var c=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(d=512,this.wb=new IntersectionObserver(a,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.wb.observe(this.c),this.rb=!0)};this.Je=function(){this.c=null;null!=this.wb&&(this.wb.disconnect(),this.qb=null,this.rb=!1)}}
function P(){this.getElementVolume_object=function(a){var c=a.getAttribute("width"),e=a.getAttribute("height");null==c||""==c||null==e||""==e?(a=a.parentNode,a={w:a.clientWidth,h:a.clientHeight}):a={w:c,h:e};return a};this.Se=function(a){var c=0;try{for(;null!=a&&10>c;){if("none"==window.getComputedStyle(a).display||"hidden"==window.getComputedStyle(a).visibility)return!1;a=a.parentElement;c++}}catch(e){}return!0};this.ca=function(a,c){this.a("cm1");var e=null,k=a.nodeName.toLowerCase();c&&this["getElementVolume_"+
k]&&(e=this["getElementVolume_"+k](a));if(!e&&(e=this.mb(a),this.a("cm2e"),!e||1>=e.w||1>=e.h))return this.a("cm1e"),{w:0,h:0};e.w.indexOf&&e.w.indexOf("px")&&(e.w=e.w.replace("px",""));e.h.indexOf&&e.h.indexOf("px")&&(e.h=e.h.replace("px",""));this.a("cm1e");return e};this.mb=function(a){this.a("cm2");try{var c;return document.body.getBoundingClientRect&&(c=a.getBoundingClientRect())?{w:c.right-c.left,h:c.bottom-c.top,l:c.left,t:c.top,Cc:c.bottom,r:c.right}:null}catch(e){return null}};this.ya=function(a){return a.document.documentElement.clientHeight?
a.document.documentElement:a.document.body};this.Nc=function(a,c){this.a("ff9");var e=0,k=!1;if(a.document.all)for(var n=0;n<a.document.all.length;n++)"BODY"==a.document.all[n].nodeName&&(k=!0),k&&("width"==c?a.document.all[n].width>e&&(e=a.document.all[n].width):a.document.all[n].height>e&&(e=a.document.all[n].height));this.a("ff9e");return e};this.$c=function(a,c){for(var e=this.ya(a),k=a.innerWidth||e.clientWidth||this.Nc(a,"width"),e=a.innerHeight||e.clientHeight||this.Nc(a,"height"),n=c.length,
l=0,r=0;r<n;r++)if(15>=Math.abs(k-c[r].w)){l=c[r].h.length;for(k=0;k<l;k++)if(15>=Math.abs(e-c[r].h[k]))return!0;break}return!1};this.Ef=function(a){for(var c=[],e=-1;c[++e]=a[e];);c.length--;return c};this.Hb=function(a,c,e,k){var n=a.getElementsByTagName("*"),n=this.Ef(n);n.unshift(a);for(var l=["EMBED","IFRAME","OBJECT","IMG","DIV"],r=[],p=0;p<n.length;p++){var d=n[p];if(-1!=l.indexOf(d.nodeName)){var h=k(d);h&&r.push({Bc:h.w*h.h,w:h.w,h:h.h,type:d.nodeName||"other",ie:d})}}r=r.sort(function(a,
d){return d.Bc-a.Bc||l.indexOf(d.type)-l.indexOf(a.type)});(c=0<r.length&&r[0].w>c&&r[0].h>e?r[0].ie:null)&&a&&(c.pb=a.pb);return c};this.Xc=function(a,c){this.a("ff10");try{if(!a)return!1;for(c||(c=window);a!=c.document&&a.parentNode;)a=a.parentNode;this.a("ff10e");return a==c.document}catch(e){return!1}};this.ac=function(a,c){var e=c.parent,k={left:0,right:0,top:0,bottom:0};if(a){var n=a.getBoundingClientRect();c!=e&&this.Mb(c,e)&&(k=this.ac(c.frameElement,e));k={left:n.left+k.left,right:n.right+
k.left,top:n.top+k.top,bottom:n.bottom+k.top}}return k};this.Mb=function(a,c){var e=!1;if(a==c)e=!0;else try{a.document.domain==c.document.domain&&(e=!0)}catch(k){}return e};this.ve=function(a){if(a)try{if(a.contentDocument&&this.Wc(a.contentDocument))return a.contentDocument;if(a.contentWindow&&this.vb(a.contentWindow))return a.contentWindow.document}catch(c){}return null};this.Rc=function(a){return a?a.defaultView||a.parentWindow:null};this.Me=function(a,c){return-1<c.indexOf(a)};this.pe=function(a){try{return a!=
a.top&&a.parent&&this.vb(a.parent)?a.parent:null}catch(c){return null}};this.vb=function(a){try{return a&&a.document&&this.Wc(a.document)?!0:!1}catch(c){return!1}};this.Wc=function(a){try{return a&&a.getElementsByTagName&&a.getElementById?!0:!1}catch(c){return!1}};this.uc=function(a,c){var e=c.parent,k={w:0,h:0,left:0,right:0,top:0,bottom:0};a&&(k=this.ac(a,c),k.w=k.right-k.left,k.h=k.bottom-k.top,c!=e&&this.Mb(c,e)&&(e=this.uc(c.frameElement,e),e.bottom<k.bottom&&(e.bottom<k.top&&(k.top=e.bottom),
k.bottom=e.bottom),e.top>k.top&&(e.top>k.bottom&&(k.bottom=e.top),k.top=e.top),e.right<k.right&&(e.right<k.left&&(k.left=e.right),k.right=e.right),e.left>k.left&&(e.left>k.right&&(k.right=e.left),k.left=e.left),k.w=k.right-k.left,k.h=k.bottom-k.top));return k};this.Sb=function(a,c){return function(){return a.apply(c,arguments)}};this.ra=function(a){try{return a?a.length?a.length:0:0}catch(c){return 0}};this.cc=function(a){for(var c=[],e=0;e<a.length;e++)this.Se(a[e])&&c.push(a[e]);return c};this.a=
function(a){try{maxLength=3,$dv&&($dv.La=$dv.La||[],$dv.La.push(a),$dv.La.length>maxLength&&$dv.La.shift())}catch(c){}};this.ye=function(){try{return $dv&&$dv.La?$dv.La.join():""}catch(a){return""}};this.ua=function(a){if(a.$sf&&a.$sf.ext)if(a.$sf.ext.geom){if(a=this.Ka(a),null!=a&&a.win&&(0<a.win.h||0<a.win.w))return this.ua=function(){return!0},!0}else if(a.$sf.ext.inViewPercentage)return!0;this.ua=function(){return!1};return!1};this.Ka=function(a){a.$sf.ext.geom&&(this.Ka="function"==typeof a.$sf.ext.geom?
function(a){return a.$sf.ext.geom()}:function(a){return a.$sf.ext.geom});return this.Ka(a)};this.F=function(a,c){if(null!=a&&null!=c)for(var e in c)c.hasOwnProperty(e)&&(a[e]=c[e])};this.jc=function(a){return a.context&&a.context.observeIntersection?!0:!1};this.tb=function(){var a=!1;if(1==this.lb("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(a=!0);return a};this.ub=function(a,c,e){var k=e&&e.Enums.BrowserId||window.$dv.Enums.BrowserId;if(a==(e&&e.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&
c.Y===k.Safari&&(null===c.ta||void 0===c.ta||!/^[3-8]/.test(c.ta)))return this.ub=function(){return!0},!0;this.ub=function(){return!1};return!1};this.lb=function(a){var c,e=this.Lc();e&&e.AVO&&(c=e.AVO[a]);return c};this.Lc=function(){var a={},c=window.$dv,e=window.$uid;c.tags&&c.tags[e]&&(a=c.tags[e]);return a};this.Eb=function(){return 1==this.lb("sam")?!0:!1};this.Ta=function(a){return a.document.hasFocus()};this.Ja=new function(){var a=this;a.cache=[];window.addEventListener?a.add=function(c,
e,k,n,l){if("undefined"==typeof n||null==n)n=window;n.addEventListener(c,e,k);l&&a.cache.push([c,e,k,n])}:window.attachEvent?a.add=function(c,e,k,n,l){if("undefined"==typeof n||null==n)n=window;n["e"+c+e]=e;n[c+e]=function(){n["e"+c+e](window.event)};n.attachEvent("on"+c,n[c+e]);l&&a.cache.push([c,e,k,n])}:a.add=function(){};window.removeEventListener?a.remove=function(a,e,k,n){if("undefined"==typeof n||null==n)n=window;n.removeEventListener(a,e,k)}:window.detachEvent?a.remove=function(a,e,k,n){if("undefined"==
typeof n||null==n)n=window;n.detachEvent("on"+a,n[a+e]);n[a+e]=null;n["e"+a+e]=null}:a.remove=function(){};a.flush=function(){for(var c=0;c<a.cache.length;c++)a.remove.apply(a,a.cache[c]);a.cache=[]}};this.getElementsByClassName=function(a,c){return a.getElementsByClassName?a.getElementsByClassName(c):a.querySelectorAll?a.querySelectorAll("."+c):[]};this.Ua=function(){var a=!1;if($dv&&$dv.CommonData){var c=$dv.CommonData.detectedDeliveryType;c&&0!=c?a=2==c||3==c:(c=$dv.CommonData.deviceType)&&(a=
2==c||3==c)}return a};this.xe=function(a,c){var e=a||"",k="";if(c&&(e+=": "+(c.message||""),c.stack)){var k=c.stack||"",n=k.indexOf("at ");0>n&&(n=0);k=", Stack: "+k.slice(n,k.length)}e=e.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");k=k.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");n=null;try{n=encodeURIComponent(e+k).slice(0,500)}catch(l){try{n=encodeURIComponent(e).slice(0,500)}catch(r){n=
e.slice(0,500)}}return n}}
function X(a,c,e,k,n,l){var r=new P;this.f=k;this.window=e;this.c=null;this.dataObj=a;this.dvObj=a.dvObj||window.$dv;this.hc=null;this.M={Y:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.R=n;this.W=this.dvObj.Enums.TrafficScenario;this.U=c;this.A=l.A;115==this.dataObj.cb&&(this.A.B.h=20,this.A.B.w=20);this.pf=function(){l.gf(this.c);this.c=null};var p=[],d=["object","embed","img","iframe"];this.dataObj.spotXmode&&(d=["object","embed",
"video","iframe"]);this.Pe=function(a){r.a("a33");a=r.ca(a);return this.Qe(a)};this.Qe=function(a){if(a){var d=a.w;a=a.h;for(var e=c.length,g=0,b=0;b<e;b++)if(15>=Math.abs(d-c[b].w))for(var g=c[b].h.length,v=0;v<g;v++)if(15>=Math.abs(a-c[b].h[v]))return!0}return!1};this.se=function(){r.a("a34");return this.te()||this.sf()};this.sf=function(){r.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),d=[],c=window.parent;r.a("ff6");try{d=c.document.getElementsByTagName("script")}catch(b){}r.a("ff6e");
for(var c=d.length,g=0;g<c;g++)if(d[g]&&d[g].id&&d[g].id.substr(7)==a)return d[g];return null};this.te=function(){r.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.Ud=function(a){r.a("a38");var c={node:a,xa:0};a=[];for(p=[];c||0<a.length;){try{var e;if(!(e=1==c.xa&&l.kc(c.node)&&!l.ka(c.node)&&l.S(c.node))){var g;a:{var b=c.node;try{if(b&&-1!=d.indexOf(b.nodeName.toLowerCase())){g=
!0;break a}}catch(k){}g=!1}e=g&&this.Pe(c.node)&&!l.ka(c.node)&&l.S(c.node)}if(e)return c;if(c.xa<=this.A.Ze){var v,x=c.node,f=c.xa,c=[],t=x.parentNode;t&&-1==p.indexOf(t)&&(p.push(t),c.push({node:t,xa:f+1}));if(x.hasChildNodes())for(var m=0;m<x.childNodes.length;m++)x.childNodes[m]&&-1==p.indexOf(x.childNodes[m])&&1===x.childNodes[m].nodeType&&(p.push(x.childNodes[m]),c.push({node:x.childNodes[m],xa:f+1}));var w,n=x,A=[],y=null;n&&n.parentNode&&(y=n.parentNode.firstChild);for(;y;)1===y.nodeType&&
y!==n&&A.push(y),y=y.nextElementSibling||y.nextSibling;w=A;for(m=0;m<w.length;m++)w[m]&&-1==p.indexOf(w[m])&&1===w[m].nodeType&&(p.push(w[m]),c.push({node:w[m],xa:f+1}));if(v=c)for(c=0;c<v.length;c++)a.push(v[c])}}catch(k){}c=a.shift()}return{node:null}};this.Ae=function(){r.a("a37");var a=this.se(),d=null;a&&(d=this.Ud(a));return d};this.ke=function(a){r.a("a31");if(this.c=l.ze())return this.f.yd(),this.hc=!0,this.c;if(this.dataObj.btreg&&!0===this.hc&&1<a)return this.c;"1"!=this.dataObj.displaynon&&
(a=this.Ae())&&a.node&&(this.f.xd(a.xa),this.c=a.node);return this.c};return this}
function aa(a,c,e,k,n,l){function r(a,b){for(var d=[],c=0;c<q.length;c++){var f=[],f=b(a,q[c]),e=h.ra(f);if(0!=e){var m=h.Rc(q[c]);if(null!=m)for(var k=0;k<e;k++)try{f[k].pb=m,d.push(f[k])}catch(l){}}}return d}function p(a,b){return r(a,function(a,g){h.a("ff4");var f=g.getElementsByTagName(a);h.a("ff4e");return"1"!=b?f:h.cc(f)})}var d=this,h=new P,u="Microsoft Internet Explorer"==navigator.appName;this.dataObj=a;this.window=c;this.c=e;this.R=k;this.W=n;this.dvObj=void 0===l?l={}:l;this.A={B:{h:1,
w:1},If:{h:10,w:10},Ze:10};115==this.dataObj.cb&&(this.A.B.h=20,this.A.B.w=20);this.Ce=function(a){if(a.scanOrder)return a.scanOrder;var b=[1==u?"object":"embed",1==u?"embed":"object","href","img","span","iframe","frameElement","div"];a.findclass&&1==a.findclass&&b.push("classDeclaration");a.gb&&0<a.gb.length&&b.unshift("searchCustomElementsFromTag");return b};this.searchCustomElementsFromTag=function(a){for(var b=0;b<a.gb.length&&(d.Ic(a.gb[b],a),!d.c);b++);};this.Gb=[["DCF",'"'],[";",";"],["%3B",
"%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.ce=function(){var g=d.dataObj.jb+"-"+d.dataObj.ib;a.isBrandShieldOrigin&&(g+="-bs");return g.replace(RegExp(",","g"),";")};this.qc=this.ce();this.Ic=function(a,b){if(b.btreg)for(var c=p(a,b.displaynon),e=h.ra(c),f=0;f<e;f++)if(c[f]&&d.wa(b,c[f],!0)&&!d.ka(c[f])){var t=this.kc(c[f]);if(t&&(m=h.ca(t))&&m.h>d.A.B.h&&m.w>d.A.B.w&&d.S(t)){d.c=t;d.S(c[f]);break}var m=h.ca(c[f]);if(m&&m.h>d.A.B.h&&
m.w>d.A.B.w&&d.S(c[f])){d.c=c[f];break}if((t=h.Hb(c[f],d.A.B.w,d.A.B.h,h.Sb(h.ca,h)))&&d.S(t)){d.c=t;d.S(c[f]);break}}};this.div=function(a){this.Ic("div",a)};this.span=function(a){h.a("a10");if(a.btreg)for(var b=p("span",a.displaynon),c=h.ra(b),e=0;e<c;e++)if(b[e]&&d.wa(a,b[e],!0)&&!d.ka(b[e])){var f=b[e];h.a("a20");if(f&&"1"==f.getAttribute("adunit")){d.c=b[e];break}if(f=this.kc(b[e])){var t=h.ca(f);if(t&&t.h>d.A.B.h&&t.w>d.A.B.w&&d.S(f)){d.c=f;d.S(b[e]);break}}if((f=h.Hb(b[e],d.A.B.w,d.A.B.h,h.Sb(h.ca,
h)))&&d.S(f)){d.c=f;d.S(b[e]);break}}};this.object=function(a){h.a("a11");for(var b=p("object",a.displaynon),c=h.ra(b),e=0;e<c;e++)if(b[e]&&d.wa(a,b[e])&&!d.ka(b[e])){var f=h.Hb(b[e],d.A.B.w,d.A.B.h,h.Sb(h.ca,h));if(f&&d.S(f)){d.S(b[e]);d.c=f;break}}};this.embed=function(a){h.a("a12");for(var b=p("embed",a.displaynon),c=h.ra(b),e=0;e<c;e++)if(b[e]&&d.wa(a,b[e])&&!d.ka(b[e])){var f=h.ca(b[e]);if(f&&f.h>d.A.B.h&&f.w>d.A.B.w&&d.S(b[e])){d.c=b[e];break}}};this.href=function(a){h.a("a13");for(var b=p("a",
a.displaynon),c=h.ra(b),e=0;e<c;e++)if(b[e]&&d.wa(a,b[e])&&!d.ka(b[e])){var f=b[e].getElementsByTagName("img");if(0<f.length){var t=h.ca(f[0]);if(t&&t.h>d.A.B.h&&t.w>d.A.B.w&&d.S(b[e])){d.c=f[0];break}}}};this.img=function(a){h.a("a14");for(var b=p("img",a.displaynon),c=h.ra(b),e=0;e<c;e++)if(b[e]&&d.wa(a,b[e])&&0>b[e].src.indexOf("event")&&!d.ka(b[e])){var f=h.ca(b[e]);if(f&&f.h>d.A.B.h&&f.w>d.A.B.w&&d.S(b[e])){d.c=b[e];break}}};this.classDeclaration=function(a){h.a("a9");var b="undefined"!==typeof window.document.getElementsByClassName,
c="undefined"!==typeof window.document.querySelectorAll;if(a.btreg){var e=[];if(b)e=d.getElementsByClassName(a.btreg,a.displaynon);else if(c)e=d.querySelectorAll(a.btreg,a.displaynon);else return;a=h.ra(e);for(b=0;b<a;b++)if(e[b]&&!d.ka(e[b])&&(c=h.ca(e[b]))&&c.h>d.A.B.h&&c.w>d.A.B.w&&d.S(e[b])){d.c=e[b];break}}};this.iframe=function(a){h.a("a15");for(var b=p("iframe",a.displaynon),c=h.ra(b),e=0;e<c&&!d.xc(a,b[e]);e++);};this.frameElement=function(a){try{h.a("a16"),k==n.SameDomain&&d.xc(a,window.frameElement)}catch(b){}};
this.getElementsByClassName=function(a,b){return r(a,function(a,d){h.a("ff1");var f=d.getElementsByClassName(a);h.a("ff1e");return"1"!=b?f:h.cc(f)})};this.querySelectorAll=function(a,b){return r(a,function(a,d){h.a("ff3");var f=d.querySelectorAll("."+a);h.a("ff3e");return"1"!=b?f:h.cc(f)})};this.la=function(a,b){h.a("a28");return!a||!b||5>b.length?!1:null!=(d.vc?d.vc(a,b):d.Ib(a,b))?!0:d.Tb&&"function"===typeof d.Tb?d.Tb(a,b):!1};this.wa=function(a,b,c){h.a("a22");var e=null;return a.btreg&&(d.vc=
1==a.Te?d.Ed:d.Ib,e=d.Kd(a,b,c))||!d.c&&(e=d.Ld(a,b))?!0:!1};this.Pd=function(a){h.a("a21");if(a&&!d.ka(a)){var b=h.ca(a);if(b&&b.h>d.A.B.h&&b.w>d.A.B.w&&d.S(a))return d.c=a,!0}return!1};this.xc=function(a,b){h.a("a17");return d.wa(a,b)?d.Pd(b):!1};this.ka=function(a){h.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var b=0;b<a.length;b++)if(a[b]==d.qc)return!0}return!1};this.S=function(a){h.a("a18");if(a&&0==d.ka(a))try{var b=a.getAttribute("dvvisit");b?a.setAttribute("dvvisit",
b+","+d.qc):(h.a("ff5"),b=window.document.createAttribute("dvvisit"),h.a("ff5e"),b.value=d.qc,a.setAttributeNode(b));return!0}catch(c){}return!1};this.gf=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.Ed=function(a,b){h.a("a29");var c;try{c=(new RegExp(b)).exec(a)}catch(e){c=d.Ib(a,b)}return c};this.Ib=function(a,b){h.a("a30");var d=null;-1!==a.indexOf(b)&&(d=a);return d};this.kc=function(a){var b=null;"celtra-ad-v3"==a.className&&a.celtra&&1==a.celtra.loaded&&
(b=a.celtra.viewabilityObservee);b&&(b.pb=h.Rc(b.ownerDocument)||window);return b};var q=[];this.Kd=function(a,b,c){h.a("a23");var e;try{if(a.Fc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(e=d.la(b.id,a.btreg))||(e=d.la(b.src,a.btreg));e||(e=d.la(b.href,a.btreg));e||(e=d.la(b.getAttribute("flashvars"),a.btreg));e||(e=d.la(b.name,a.btreg));!e&&a.findclass&&1==a.findclass&&(e=d.la(b.getAttribute("class"),a.btreg));if(!e&&d.dataObj.Ia&&0<d.dataObj.Ia.length)for(var f=d.dataObj.Ia,t=0;t<f.length&&
!(e=d.la(b.getAttribute(f[t]),a.btreg));t++);e||c||(e=d.la(b.innerHTML,a.btreg));e&&!c&&(e=d.Jd(a,b));return e}catch(m){return e}};this.Da=function(a,b){h.a("a25");if(!a)return!1;a=a.toLowerCase();for(var c=0;c<d.Gb.length;c++){var e;if(b.Ac&&(e=(d.Gb[c][0]+b.Ac).toLowerCase(),e=a.indexOf(e),-1<e)||b.ed&&(e=(d.Gb[c][0]+b.ed).toLowerCase(),e=a.indexOf(e),-1<e))return!0}return!1};this.Ld=function(a,b){h.a("a24");var c;try{if(a.Fc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(c=d.Da(b.id,a))||
(c=d.Da(b.src,a));c||(c=d.Da(b.href,a));c||(c=d.Da(b.Nf,a));c||(c=d.Da(b.name,a));c||(c=d.Da(b.innerHTML,a));if(!c&&d.dataObj.Ia&&0<d.dataObj.Ia.length)for(var e=d.dataObj.Ia,f=0;f<e.length&&!(c=d.la(b.getAttribute(e[f]),a.btreg));f++);return c}catch(t){return c}};this.Jd=function(a,b){h.a("a26");return null==a.Qa||""==a.Qa?!1:d.la(d.Dd(b),a.Qa)};this.searchByAdSrvId_8=function(a,b){h.a("a1");var d=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=d&&(d=d.toString(),d.replace(RegExp("-","g"),"")==
b)?!0:!1};this.Tb=this["searchByAdSrvId_"+(d.dataObj?d.dataObj.cb||"":"")];this.Dd=function(a){h.a("a27");if(a.outerHTML)return a.outerHTML;for(var b=a.attributes.length,d="",c=0;c<b;c++)d=d+a.attributes[c].nodeName+"="+a.attributes[c].nodeValue+" ";return d+a.innerHTML};this.ze=function(){h.a("32");var a=[];void 0===l.tags&&(l.tags={});void 0===l.tags[$uid]&&(l.tags[$uid]={});void 0!==l.tags[$uid].spvi&&(a.push(l.tags[$uid].spvi),-1<a[0].scanOrder.indexOf(",")&&(a[0].scanOrder=a[0].scanOrder.split(",")));
d.dataObj.scanOrder=this.Ce(d.dataObj);a.push(d.dataObj);var b=d.window,c=0,k=[];try{do{k.push(b.document);for(var f=k,t=b.document.getElementsByTagName("iframe")||[],m=0;m<t.length||25>m;m++){var w=null,w=h.ve(t[m]);void 0!==w&&null!==w&&0==h.Me(w,f)&&f.push(w)}b=h.pe(b)}while(b&&10>++c)}catch(n){}q=k;for(b=0;b<a.length;b++)for(c=a[b],k=0;k<c.scanOrder.length;k++)if(void 0!=d[c.scanOrder[k]]&&(d[c.scanOrder[k]](c),d.c))return $dv&&$dv.eventBus&&$dv.eventBus.dispatchEvent&&$dv.eventBus.dispatchEvent(window,
"avsAdFound",{timeStamp:(new Date).getTime(),adDomElement:d.c}),d.c;return e};return this}
function dv_CustomClientViewAssureService(a){function c(a){return{nf:{adView:a.rq.av,Le:a.rq.ic,yc:a.rq.adc,Ye:a.rq.mla,bd:a.rq.ldav,focus:a.rq.fc,zc:a.rq.as},mf:{dd:a.rp.mt,ff:a.rp.pt,$e:a.rp.mr,ef:a.rp.pr,eventId:a.rp.eid,Ec:a.rp.bl}}}this.Td=dv_InViewService;this.Td(a);this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this.b=new P;this.$a=[];a=$dv.tags[$uid].dc||a.dc||[];var e=this.b.Lc().bgm,k;for(k in a)a.hasOwnProperty(k)&&this.$a.push(new window.Xb.de(c(a[k]),e));
var n=this.Jb;this.Jb=function(a){a=n(a);for(var c=0;c<this.$a.length;c++)this.$a[c].fe(a,this.$.interval);return a};var l=this.Oa;this.Oa=function(a,c){l(a,c);if(1==this.Ub)for(var d=0;d<this.$a.length;d++)this.$a[d].bf()}}window.Xb=window.Xb||{};
window.Xb.de=function(a,c){function e(a){a.s&&a.s.g&&a.s.g.m&&a.s.g.o&&242500<=a.s.g.o*a.s.g.m&&(l=!0,k.bd&&(k.adView=k.bd),e=function(){})}var k=a.nf,n=a.mf,l=!1;this.fe=function(a,c){e(a);var l=!0,n;n=k.focus?a.j:a.ja;k.adView&&k.adView>n&&(l=!1);k.zc&&a.s&&a.s.g&&a.s.g.m&&a.s.g.o&&a.s.g.o*a.s.g.m<k.zc&&(l=!1);l?r+=c:k.Le&&(r=0);this.Yd(a)};var r=0;this.bf=function(){this.jf(n.dd,n.$e,n.Ec)};this.jd=function(){this.kf(n.dd,n.ff,n.ef,n.Ec,n.eventId);this.jd=function(){}};this.Yd=function(a){(k.yc&&
r>=k.yc||l&&k.Ye)&&this.jd(a)};var p;this.jf=function(a,e,k){c&&k||(a&&(p=$dv.tags[$uid].getTimeDiff(),k={},k[a]=p,$dv.registerEventCall($uid,k)),e&&($dv.pubSub.publish(e,$uid),window&&$dv.pubSub.publish(e,window.$frmId)))};this.kf=function(a,e,k,l,g){c&&l||(e&&(l={},l[e]=$dv.tags[$uid].getTimeDiff(),g&&(l.evid=g),a&&(l[a]=p||$dv.tags[$uid].getTimeDiff()),$dv.registerEventCall($uid,l)),k&&($dv.pubSub.publish(k,$uid),window&&$dv.pubSub.publish(k,window.$frmId)))}};
function dv_InViewService(a){function c(){null===l.interval&&(l.interval=setInterval(l.we(),l.$.interval))}function e(){if(!1===l.Zc){l.Zc=!0;try{l.b.Ja.remove("load",arguments.callee,!1,element)}catch(a){}l.Ab();l.b.a("s41");l.sa=new W(l.Xd?l.Xd:l.window,l.c,l.R,l.M,l.N,l.f.Gc,l.dvObj,l.impressionId);l.b.a("s42");l.Gd();l.start()}}function k(a,b){return a.isReportingDisabled?new S:new R(a,b)}function n(a,b){l.b.Ja.add("click",function(){l.Nb(!0);$dv.registerEventCall(l.impressionId,"ad"==b?{dvp_csad:1}:
{dvp_csifr:1});l.b.Ja.remove("click",arguments.callee,!1,a)},!1,a,!1)}var l=this;this.cd=10;this.Sd=a.serverSettings&&a.serverSettings.jsVersion?a.serverSettings.jsVersion:"669";this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this._minor_version="0";this.b=new P;this.Ie=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,d=0;d<b;d++)if(c=a[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};var r=this.Zc=!1,p=!1;this.Fe=function(){var a=
"";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.Qc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.V=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.Ge=function(){var a=this.V("uid",this.ba);null==
a?(a=this.Qc(),this.ba=this.ba+"&uid="+a):""==a&&(a=this.Qc(),this.ba=this.ba.replace("&uid=","&uid="+a));return a};this.oc=function(a,b,c,d){if(d&&d.insertBefore&&d.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in c)a.style[e]=c[e];d.insertBefore(a,d.firstChild);return a}return null};this.Wd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};
this.R=this.dvObj.CommonData.Scenario||this.Wd();this.M={Y:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.W=this.dvObj.Enums.TrafficScenario;this.Xa="default";this.dataObj=a;this.window=a.tagWindow||parent.window||window;this.c=null;this.sc=this.Pa=!1;this.lc=!0;this.interval=null;this.ba=this.Ie();this.Ba=this.Fe();a.serverSettings&&a.serverSettings.protocol&&a.serverSettings.protocol.indexOf("http");this.$=window.he||this.window.he||
{interval:100,za:{"default":{time:null,Ja:["beforeunload","unload"],td:9E5}}};this.gd={};var d=null;this.T=window.ge||this.window.ge||{interval:1E3,aa:6};var h=a&&a.vd?a.vd:!1;a=a&&a.wd?a.wd:!1;!1!==h&&!1!==a&&(this.T.interval=h,this.T.aa=a,$dv.registerEventCall(this.impressionId,{Lf:this.T.interval,Mf:this.T.aa}));h=this.b.Ua();this.ae={hb:12,Wb:10,Wa:30};this.N={Firefox:{X:115},Chrome:{X:89},Safari:{X:38},Explorer:{X:55},cf:500,Ua:h,Wa:30};var u=!1,q=0,g=[5,10,15];window.devicePixelRatio&&(this.N.Firefox.X=
0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.U=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050,413]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,
h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180]},{w:980,
h:[90,120]},{w:900,h:[240]},{w:275,h:[300]}];this.dataObj.spotXmode&&(this.U.push({w:320,h:[240]}),this.U.push({w:400,h:[300]}),this.U.push({w:450,h:[338]}),this.U.push({w:600,h:[800]}),this.U.push({w:640,h:[360]}),this.U.push({w:854,h:[480]}),this.U.push({w:500,h:[375]}));h&&(this.U.push({w:320,h:[50,100,480]}),this.U.push({w:300,h:[50,31]}),this.U.push({w:120,h:[20]}),this.U.push({w:168,h:[28]}),this.U.push({w:216,h:[36]}),this.U.push({w:292,h:[30]}));this.ob=this.Ge();this.Vb=!1;this.Na=function(a,
b){this.window.Jc||(this.window.Jc=[]);this.window.Jc.push({caller:a,Of:b})};this.startTime=(new Date).getTime();this.Qd=4;this.wc=0;this.ec=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,Jf:17,interval:32};this.Ub=!1;this.ud=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.f.qe();this.window.dv_logObject[this.ob]=a}this.b.a("ie16e")};this.Db=function(a){this.b.a("ie17");this.Db=this.Vb?function(a){this.f.od(a);
this.ud()}:function(a){this.f.od(a)};this.Db(a)};this.rc=function(a,b){this.rc=this.Vb?function(a,f){this.f.nd(a,f);this.ud()}:function(a,f){this.f.nd(a,f)};this.rc(a,b)};this.Ab=function(){this.b.a("s4");this.c=this.Qb.ke(this.T.aa);!this.c&&this.R==this.W.CrossDomain&&this.b.ua(this.window)&&(this.T.aa=0);if(this.c)this.tf(),this.f.hf(this.c),r||(n(this.c,"ad"),r=!0),p||this.R!=this.W.CrossDomain&&this.R!=this.W.SameDomain||(n(window.parent,"ifr"),p=!0),setTimeout(c,this.Qb.hc?10:50);else if(0<
this.T.aa)this.T.aa--,this.uf(),setTimeout(this.le(),this.T.interval);else{try{this.R==this.W.CrossDomain&&(this.b.$c(this.window,this.U)||this.b.ua(this.window))?(this.c=this.b.ya(this.window),this.f.md()):this.R==this.W.SameDomain&&this.b.$c(this.window,this.U)?(this.c=this.b.ya(window.parent),this.f.md(),this.$d()):this.T.aa=-1}catch(a){this.T.aa=-1}setTimeout(c,10)}this.b.a("s4e")};this.$d=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),
c=b.length,d=0;d<c;d++)b[d].contentWindow==a&&(this.c=b[d],this.window=a.parent);this.b.a("ff26e")};this.uf=function(){this.dataObj.btreg&&this.dataObj.Qa?this.f.yf():this.f.zf()};this.tf=function(){this.b.a("s9");this.Pa=!0;this.f.vf();this.b.a("s9e")};this.Rd=function(){this.dataObj.cb=this.V("adsrv",this.ba)||"";this.dataObj.btreg=this.V("btreg",this.ba)||"";this.dataObj.ed=this.V("plcid",this.ba)||"";"8"==this.dataObj.cb&&""==this.dataObj.btreg&&(this.dataObj.btreg=this.dataObj.plcid);this.dataObj.Qa=
this.V("btadsrv",this.ba)||"";this.dataObj.Ac=this.V("adid",this.ba)||"";this.dataObj.ob=this.ob;this.dataObj.Te=this.V("isbtregex",this.Ba)||"";this.dataObj.jb=this.V("ctx",this.ba)||"";this.dataObj.ib=this.V("cmp",this.ba)||"";this.dataObj.Ue=this.V("lomd",this.Ba)||"";this.dataObj.findclass=this.V("findclass",this.Ba)||"";this.dataObj.displaynon=this.V("displaynon",this.Ba)||"";this.dataObj.Fc=this.V("bsdvview",this.Ba)||"";var a=this.V("bttag",this.Ba)||"";this.dataObj.gb=0<a.length?a.split("|"):
[];a=this.V("btattb",this.Ba)||"";this.dataObj.Ia=0<a.length?a.split("|"):[]};this.fd=function(a){a=this.xb(a);return 0<a.length?{tagServiceResult:a.join(",")}:{}};this.xb=function(a){if(!this.dvObj)return[];for(var b=[],c=0;c<a.length;c++){var d=this.dvObj.pubSub.publish(a[c],this.impressionId)||null;null!=d&&b.push(d);window&&(d=this.dvObj.pubSub.publish(a[c],window.$frmId)||null,null!=d&&b.push(d))}return b};this.zd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.ba+=
"&TKH="+this.dataObj.serverSettings.TKH)};this.ee=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.ee();this.zd();this.Rd();
this.f=new G(this.Sd,this.ae,this.dataObj);this.ha=k(this.dataObj,this.f);this.dataObj.isRTNsDisabled&&(this.xb=function(){return[]});this.Vb=this.window.dv_logObject?!0:!1;this.Af();this.Vd=new aa(this.dataObj,this.window,this.c,this.R,this.W,this.dvObj);this.Qb=new X(this.dataObj,this.U,this.window,this.f,this.R,this.Vd);var a=window.parent;"589953"==this.dataObj.jb&&"587351"==this.dataObj.ib||"589953"==this.dataObj.jb&&"616389"==this.dataObj.ib||"polite"==this.dataObj.Ue?(setTimeout(e,15E3),this.b.Ja.add("load",
function(){setTimeout(e,1E3)},!1,a,!1)):e()}catch(b){var c=this;this.Ea(function(){c.Na("inViewManager",b);c.f.Za("inViewManager",b);c.ha.da(c.logEvents.errorlevel1)},"inViewManager",b)}};this.ab=function(a){this.b.a("ie20");-6!=a.j&&(-3==a.j||-5!=a.j&&0>a.j&&-1==this.T.aa)&&(this.tc(),this.ab=function(){})};this.tc=function(){this.ha.da(this.logEvents.nonMeasurable);this.xb(["IABNotMeasuredImpression"]);this.tc=function(){}};this.Oa=function(a,b){a.b.a("ie21");if(0<=b.j||-5==b.j&&-1>=a.T.aa){if(a.dvObj&&
a.impressionId){a.b.a("ie23");var c=a.fd(["IABMeasuredImpression"]);a.b.a("ie24");a.ha.da(a.logEvents.startMeasure,c)}else a.ha.da(a.logEvents.startMeasure);a.Ub=!0;a.Oa=function(){};a.ab=function(){}}a.b.a("ie22")};this.Nb=function(a){this.b.a("ie25");if(this.f.Mc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),a=this.fd(["IABViewableImpression"]),this.b.a("ie29"),this.ha.da(this.logEvents.iabViewable,a)):this.ha.da(this.logEvents.iabViewable),u=!0,this.Nb=function(){};
this.b.a("ie26")};this.be=function(a){if(u&&this.f.Mc())for(q+=a,a=0;a<g.length;a++)null!=g[a]&&q>=1E3*g[a]&&(this.xb(["IABAdViewable"+g[a]+"Seconds"]),g[a]=null);else q=0};var b="hidden",v=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(var a in vis)if(vis[a]in document){b=vis[a];break}a=1==this.b.lb("fcs");var c=!1;try{this.b.Ta(this.window),c=!0}catch(d){}var e=!1;try{this.b.Ta(this.window.top),e=!0}catch(d){}var g=null,g=a&&c&&this.M.Y==this.Z.IE?
function(){var a=l.b.Ta(l.window);l.R==l.W.OnPage&&(a=a&&l.lc);return a}:a&&e?function(){var a=!0,a=l.b.Ta(l.window.top);l.R==l.W.OnPage&&(a=a&&l.lc);return a}:"undefined"!==typeof document[b]?function(){return!l.window.document[b]}:e?function(){return l.b.Ta(l.window.top)}:function(){return!0};this.hasFocus=function(){try{return g()}catch(a){v++,5<=v&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.bc=function(a){var b=a.sa.ue();a.b.a("ie12");0>b.j&&this.f.Cb(Math.abs(b.j));
null==this.c||-3==b.j||a.hasFocus()||(b.j=0,this.f.Cb(9));a.b.a("ie13");return d=b};var x;this.Jb=function(a){var b;try{$uid&&dvObj&&dvObj.tags[$uid]&&dvObj.tags[$uid].getTimeDiff&&(b=dvObj.tags[$uid].getTimeDiff())}catch(c){}a.$.interval=b-x||100;x=b;a.b.a("ie1");b=a.c?a.c.pb||a.window:a.window;a.sa.c=a.c;a.sa.window=b;a.b.a("ie2");b=a.bc(a);a.Pa&&(-1==b.j||-2==b.j)&&-1<=a.T.aa&&(a.kd(a),a.Ab());a.b.a("ie3");-5==b.j&&(a.T.aa--,a.f.pd(),a.Ma||(a.Ma=function(b){b=a.sa.sb(b);a.f.Ya(b)}));a.b.a("ie4");
a.Ma&&0<b.j&&(a.Ma(b),a.Ma=null);a.b.a("ie5");if(a.Pa&&!a.sc){a.sc=!0;var d=a.sa.sb(b);a.f.Ya(d)}-5==b.j&&-1<=a.T.aa&&(a.kd(a),a.Ab(),b=a.bc(a),-5==b.j&&0<a.T.aa&&a.f.qf());a.b.a("ie6");a.rc(b,a.$.interval);a.b.a("ie7");a.Db(b);a.b.a("ie8");a.f.rd(b.fa);a.ab(b);a.b.a("ie9");a.Oa(a,b);a.b.a("ie10");a.Nb();a.b.a("ie11");a.be(a.$.interval);a.b.a("ie12");return b};this.kd=function(a){a.Pa=!1;a.c=null;a.Qb.pf();a.sa.Je()};this.we=function(){this.b.a("s26");var a=this;return function(){try{a.Jb(a)}catch(b){a.Ea(function(){a.wc<
a.Qd&&(a.wc++,a.Na("getIntervalCallback",b),a.f.Za("getIntervalCallback",b),a.ha.da(a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Pc=function(a){var b=this;return function(){b.Ea(function(){b.ha.da(b.logEvents[a])},"getReportEventCallback")}};this.le=function(){var a=this;return function(){a.Ea(function(){a.Ab();a.c||a.f.Bb()},"getAdLocateCallback")}};this.Sa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.lc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){a.Ea(function(){a.Na("getFocBluEventCallback",
c);a.f.Za("getFocBluEventCallback",c);a.ha.da(a.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.Fd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.f.re().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*
c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.Ub,totalPageTime:(a.f.$b()-a.f.Ee())/1E3,notApplicableTime:a.f.Oc()/1E3}}catch(e){return{}}}}}catch(b){}};this.Gd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=d.j;0<=d.j&&d.s&&d.s.g&&(a.adWidth=d.s.g.o,a.adHeight=d.s.g.m);return a};a.VA.getAdElem=function(){return l.c}}}catch(b){}};this.Fd();this.start=
function(){this.b.a("s35");this.df(this);var a;this.$&&this.$.za&&this.$.za[this.Xa]&&(a=this.$.za[this.Xa].Ja);if(a)for(var b=a.length,c=0;c<b;c++)this.gd[a[c]]=this.Pc(a[c]),this.Ha(this.window,a[c],this.gd[a[c]]);this.Cf();this.$&&this.$.za&&this.$.za[this.Xa]&&this.$.za[this.Xa].td&&setTimeout(this.lf(),this.$.za[this.Xa].td)};this.lf=function(){var a=this;return function(){a.Pc("timeout")();clearInterval(a.interval);a.ha.da=function(){}}};this.df=function(a){try{var b=a.bc(a);-5==b.j&&(this.f.pd(),
this.Ma||(this.Ma=function(b){b=a.sa.sb(b);a.f.Ya(b)}));if(a.Pa)if(this.sc=!0,-5!=b.j){var c=a.sa.sb(b);a.f.Ya(c)}else a.f.Ya("true");a.f.rd(b.fa);var d=a.sa.ne(b,a.f.Oc());a.f.xf(d);a.f.qd(b.j);a.Db(b);a.ab(b);a.Oa(a,b)}catch(e){a.Ea(function(){a.Na("onStartReport",e);a.f.Za("onStartReport",e);a.ha.da(a.logEvents.errorlevel1)},"onStartReport",e)}};this.Cf=function(){this.Ha(this.window,"blur",this.Sa());this.Ha(this.window,"focus",this.Sa());this.Ha(this.window.document,"click",this.Sa());this.Ha(this.window.document,
"mousedown",this.Sa());this.Ha(this.window.document,"mouseup",this.Sa())};this.Ha=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.Af=function(){this.b.a("ff24");this.R==this.W.CrossDomain?this.b.ua(this.window)||this.b.jc(this.window)||this.b.tb()||this.b.ub(this.R,this.M,this.dvObj)||(this.M.Y!=this.Z.Firefox&&
this.M.Y!=this.Z.IE?this.f.Bf():this.M.Y==this.Z.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.f.pc()):window.document.body.getBoundingClientRect||this.f.pc();this.ec=this.f.Gc();this.b.a("ff24e")};this.Ea=function(a,b,c){try{a()}catch(d){try{0<this.cd&&(this.cd--,a=c||d,b=b||"unknown caller",this.Na(b,a),this.f.Za(b,a),this.ha.da(l.logEvents.errorlevel1))}catch(e){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(a){(new dv_CustomClientViewAssureService(a)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs669");
if(tagObject){var serviceParams=tagObject.services.avs669;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(a){};
